on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: busybox
    steps:
      - id: setup
        name: Simulate long running process
        run: |
          echo Sleeping for 600s
          sleep 600
          echo "reached-end=true" >> $GITHUB_OUTPUT

      - name: Check result
        env:
          REACHED_END: ${{ steps.setup.outputs.reached-end }}
        run: |
          ps -ef
          [ -n "$REACHED_END" ]
        
